/* eslint-disable */
/*
  THIS FILE IS AUTOGENERATED. DO NOT EDIT BY HAND.
  Source of truth: spec/CONTRACTS.md
*/

export const ReservationStatus = ["pending", "confirmed", "cardPlaced", "seated", "completed", "noshow", "cancelled", "refused", "incident"] as const;
export type ReservationStatus = (typeof ReservationStatus)[number];

export const ErrorCode = ["VALIDATION_ERROR", "TURNSTILE_FAILED", "RATE_LIMITED", "SLOT_TAKEN", "INSUFFICIENT_CAPACITY", "TOKEN_INVALID", "TOKEN_EXPIRED", "VERSION_CONFLICT", "TABLE_CONFLICT", "FORBIDDEN", "NOT_FOUND", "SAME_TYPE_OVERLAP"] as const;
export type ErrorCode = (typeof ErrorCode)[number];

export const Service = ["lunch", "dinner"] as const;
export type Service = (typeof Service)[number];

export const Language = ["fr", "nl", "en", "de", "it"] as const;
export type Language = (typeof Language)[number];

export const SlotTakenReason = ["closed", "taken"] as const;
export type SlotTakenReason = (typeof SlotTakenReason)[number];

export const ExpectedQueries = [
  "availability.getDay",
  "availability.getMonth",
  "reservations.getByToken",
  "reservations.listByService",
  "reservations.listPending",
  "reservations.getAdmin",
  "reservations.getStaff",
  "floor.getTables",
  "admin.getSettings",
  "widget.getSettings"
] as const;
export type ExpectedQueryName = (typeof ExpectedQueries)[number];

export const ExpectedMutations = [
  "reservations._create",
  "reservations._cancel",
  "reservations.adminConfirm",
  "reservations.adminRefuse",
  "reservations.adminCancel",
  "reservations.checkIn",
  "reservations.checkOut",
  "floor.assignTables",
  "floor.upsertTable",
  "availability.adminOverrideSlot",
  "admin.updateSettings",
  "admin.updateSecrets"
] as const;
export type ExpectedMutationName = (typeof ExpectedMutations)[number];

export const ExpectedActions = [
  "reservations.create",
  "groupRequests.create",
  "reservations.cancelByToken",
  "email.processQueue",
  "email.sendJob"
] as const;
export type ExpectedActionName = (typeof ExpectedActions)[number];

export function makeSlotKey(args: { dateKey: string; service: Service; timeKey: string }): string {
  return `${args.dateKey}#${args.service}#${args.timeKey}`;
}

export function parseSlotKey(slotKey: string): { dateKey: string; service: Service; timeKey: string } {
  const [dateKey, service, timeKey, ...rest] = slotKey.split("#");
  if (!dateKey || !service || !timeKey || rest.length > 0) {
    throw new Error("Invalid slotKey");
  }
  if (!(Service as readonly string[]).includes(service)) {
    throw new Error("Invalid service in slotKey");
  }
  return { dateKey, service: service as Service, timeKey };
}

export function computePartySize(adults: number, childrenCount: number, babyCount: number): number {
  return adults + childrenCount + babyCount;
}

export function computeEffectiveOpen(isOpen: boolean, capacity: number): boolean {
  return isOpen === true && capacity > 0;
}

import { z } from "zod";

export const ErrorCodeSchema = z.enum(ErrorCode);
export const ErrorShapeSchema = z.object({
  code: ErrorCodeSchema,
  messageKey: z.string(),
  meta: z.record(z.string(), z.unknown()).optional(),
});

export const RateLimitedMetaSchema = z.object({ retryAfterMs: z.number() });
export const SlotTakenMetaSchema = z.object({
  slotKey: z.string(),
  reason: z.enum(SlotTakenReason).optional(),
});
export const InsufficientCapacityMetaSchema = z.object({
  slotKey: z.string(),
  requestedPartySize: z.number(),
  remainingCapacity: z.number(),
});
export const VersionConflictMetaSchema = z.object({ expectedVersion: z.number(), actualVersion: z.number() });
export const TableConflictMetaSchema = z.object({ slotKey: z.string(), tableIds: z.array(z.string()) });

export const SettingsPublicSchema = z.object({
  restaurantId: z.string(),
  publicWidgetEnabled: z.boolean(),
  turnstileSiteKey: z.string(),
  maxPartySizeWidget: z.number(),
  timezone: z.string(),
}).strict();

export const SettingsAdminSchema = SettingsPublicSchema.extend({
  resendFromEmail: z.string(),
  resendFromName: z.string(),
  manageTokenExpireBeforeSlotMs: z.number(),
  rateLimit: z.object({ windowMs: z.number(), maxRequests: z.number() }),
}).strict();

export const SlotSchema = z.object({
  slotKey: z.string(),
  dateKey: z.string(),
  service: z.enum(Service),
  timeKey: z.string(),
  isOpen: z.boolean(),
  capacity: z.number(),
  remainingCapacity: z.number(),
  maxGroupSize: z.number().nullable(),
}).strict();
